apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: my-ingress
spec:
  rules:
    - host: student.io
      http:
        paths:
          - backend:
              serviceName: my-service
              servicePort: 8880
